MVCRosterCalc_DONOTZIP/FootballCalc/Models/Roster.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FootballCalc.Models
{
    public class Roster
    {
        [Key]
        public int RosterID { get; set; }
        public List<Players> players { get; set; } = new List<Players>();

        public int TotalPrice() => players.Count > 0 ? players.Select(p => p.PlayerSalary).Sum() : 0;

        public int NumOfPlayersForPosition(int pos) => players.Where(p => p.PlayerPosition == pos).Count();
    }
}

MVCRosterCalc_DONOTZIP/FootballCalc/Controllers/RosterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FootballCalc.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;

namespace FootballCalc.Controllers
{
    public class RosterController : Controller
    {
        List<Roster> RosterList;

        private void GetRosterList()
        {
            var value = HttpContext.Session.GetString("Rosters");
            if (value == null)
            {
                RosterList = new List<Roster>();
            }
            else
            {
                RosterList = JsonConvert.DeserializeObject<List<Roster>>(value);
            }
        }

        public IActionResult Index()
        {
            GetRosterList();

            return View(RosterList);
        }

        public IActionResult Details(int id)
        {
            GetRosterList();
            return View(RosterList[id - 1]);
        }

        public IActionResult Remove(int id)
        {
            GetRosterList();
            RosterList.Remove(RosterList[id]);
            HttpContext.Session.SetString("Rosters", JsonConvert.SerializeObject(RosterList));
            return RedirectToAction("Index");
        }
    }
}

MVCRosterCalc_DONOTZIP/FootballCalc/Views/Roster/Details.cshtml
@model FootballCalc.Models.Roster

@{
    ViewData["Title"] = "Details";
}

<h1>Roster @Model.RosterID</h1>
<b>Roster Cost: $@Model.TotalPrice().ToString("0.00")</b>

<table class="table" style="color: white;">
    <thead>
        <tr>
            <th>
                Player Name
            </th>
            <th>
                Player Team
            </th>
            <th>
                Salary
            </th>
            <th>
                Player Position
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.players)
        {
            <tr>
                <td>@item.PlayerName</td>
                <td>@item.PlayerTeam</td>
                <td>@item.PlayerSalary</td>
                <td>@Enum.GetName(typeof(enumPositions), @item.PlayerPosition)</td>
            </tr>
        }
    </tbody>
</table>

<a asp-action="Index" asp-controller="Roster">Back</a> |
<a asp-action="Remove" asp-controller="Roster">Remove Roster?</a>

MVCRosterCalc_DONOTZIP/FootballCalc/Views/Roster/Index.cshtml
@model IEnumerable<FootballCalc.Models.Roster>

@{
    ViewData["Title"] = "Rosters";
}

<h1>All of Your Rosters</h1>

<table class="table" style="color: white;">
    <thead>
        <tr>
            <th>Roster</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@for (int i = 1; i <= Model.Count(); i++)
{
        <tr>
            <td>
                Roster @i
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@i">Details</a> |
                <a asp-action="Remove" asp-route-id="@i">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MVCRosterCalc_DONOTZIP/FootballCalc/Views/Roster/View.cshtml
@{
    ViewData["Title"] = "View";
}

<h1>View</h1>