MVCRosterCalc_DONOTZIP/FootballCalc/Controllers/AddPlayersController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using FootballCalc.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace FootballCalc.Controllers
{
    public class AddPlayersController : Controller
    {
        private readonly DbApiContext _context;

        public AddPlayersController(DbApiContext context)
        {
            _context = context;
        }

        List<Players> PlayersList;

        // GET: AddPlayers
        private void GetPlayerList()
        {
            var value = HttpContext.Session.GetString("Players");
            if (value == null)
            {
                PlayersList = new List<Players>();
            }
            else
            {
                PlayersList = JsonConvert.DeserializeObject<List<Players>>(value);
            }
        }


        public IActionResult Index()
        {
            GetPlayerList();
            return View(PlayersList);
            //return View(await _context.players.ToListAsync());
        }

        [HttpPost, ActionName("Index")]
        public IActionResult AddPlayer(string name, int position, string team, int salary)
        {
            GetPlayerList();
            Players player = new Players
            {
                PlayerID = PlayersList.Any() ? PlayersList.Max(p => p.PlayerID) + 1 : 1,
                PlayerName = name,
                PlayerPosition = position,
                PlayerTeam = team,
                PlayerSalary = salary
            };
            PlayersList.Add(player);
            HttpContext.Session.SetString("Players", JsonConvert.SerializeObject(PlayersList));
            return RedirectToAction("Index");
        }

        [ActionName("Index")]
        [HttpGet("{id}")]
        public ActionResult RemovePlayer(int id)
        {
            GetPlayerList();
            PlayersList.Remove(PlayersList.FirstOrDefault(p => p.PlayerID == id));
            HttpContext.Session.SetString("Players", JsonConvert.SerializeObject(PlayersList));
            return RedirectToAction("Index");
        }


        // GET: AddPlayers/Delete
        public IActionResult Delete()
        {
            GetPlayerList();
            if (PlayersList == null)
            {
                return RedirectToAction("Index");
            }

            return View();
        }

        // POST: AddPlayers/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed()
        {
            PlayersList = new List<Players>();
            HttpContext.Session.SetString("Players", JsonConvert.SerializeObject(PlayersList));
            return RedirectToAction("Index");
        }

        private bool PlayersExists(int id)
        {
            return _context.Players.Any(e => e.PlayerID == id);
        }

        [HttpPost]
        public IActionResult CreateRosters(int budget, int qb, int wr, int te, int rb, int flex, int dsp)
        {
            GetPlayerList();
            List<Roster> rosters = new List<Roster>();

            var rand = new Random();
            List<int> positionNumbers = new List<int>();
            positionNumbers.Add(qb);
            positionNumbers.Add(wr);
            positionNumbers.Add(te);
            positionNumbers.Add(rb);
            positionNumbers.Add(flex);
            positionNumbers.Add(dsp);

            PlayersList = PlayersList.OrderBy(p => p.PlayerSalary).ToList();

            for (int i = 0; i < PlayersList.Count; i++)
            {
                bool cont = true;
                Roster roster = new Roster();

                for (int y = i; y < PlayersList.Count; y++)
                {
                    Players player = PlayersList[y];

                    if (roster.TotalPrice() + player.PlayerSalary > budget) continue;
                    if (roster.NumOfPlayersForPosition(player.PlayerPosition) >= positionNumbers[player.PlayerPosition]) continue;

                    roster.players.Add(player);
                }

                for (int x = 0; x < positionNumbers.Count(); x++)
                {
                    if (roster.NumOfPlayersForPosition(x) < positionNumbers[x])
                        cont = false;
                }

                if (!cont) break;
                else rosters.Add(roster);
            }


            HttpContext.Session.SetString("Rosters", JsonConvert.SerializeObject(rosters));

            return RedirectToAction("Index", "Roster");
        }
    }
}

MVCRosterCalc_DONOTZIP/FootballCalc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using FootballCalc.Models;

namespace FootballCalc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        
        public IActionResult List()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCRosterCalc_DONOTZIP/FootballCalc/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FootballCalc.Models;

namespace FootballCalc.Controllers
{
    public class PlayersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PlayersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Players
        public async Task<IActionResult> Index()
        {
            return View(await _context.player.ToListAsync());
        }

        // GET: Players/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var players = await _context.player
                .FirstOrDefaultAsync(m => m.PlayerID == id);
            if (players == null)
            {
                return NotFound();
            }

            return View(players);
        }

        // GET: Players/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Players/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PlayerID,RosterID,PlayerName,PlayerSalary")] Players player)
        {
            if (ModelState.IsValid)
            {
                _context.Add(player);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(player);
        }

        // GET: Players/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var players = await _context.player.FindAsync(id);
            if (players == null)
            {
                return NotFound();
            }
            return View(players);
        }

        // POST: Players/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PlayerID,RosterID,PlayerName,PlayerSalary")] Players player)
        {
            if (id != player.PlayerID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(player);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlayersExists(player.PlayerID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(player);
        }

        // GET: Players/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var players = await _context.player
                .FirstOrDefaultAsync(m => m.PlayerID == id);
            if (players == null)
            {
                return NotFound();
            }

            return View(players);
        }

        // POST: Players/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var players = await _context.player.FindAsync(id);
            _context.player.Remove(players);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlayersExists(int id)
        {
            return _context.player.Any(e => e.PlayerID == id);
        }
    }
}

MVCRosterCalc_DONOTZIP/FootballCalc/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FootballCalc.Models;

namespace FootballCalc.Controllers
{
    public class RegisterController : Controller
    {
        private IFootballRepository repository;
        public RegisterController(IFootballRepository repo)
        {
            repository = repo;
        }
        public ViewResult List() => View(repository.Users);
        
    }
}

MVCRosterCalc_DONOTZIP/FootballCalc/Views/Home/Index.cshtml
@{
    <title>@ViewData["Title"] - Fantasy Roster Calculator</title>
}
<div>
    @Html.ActionLink("Team Roster", "Index", "Players")
    <br />
    @Html.ActionLink("Add Player", "Index", "AddPlayers")
</div>

MVCRosterCalc_DONOTZIP/FootballCalc/Views/Home/List.cshtml
@model IEnumerable<UserModel>

@foreach (var p in Model)
{
    <div>
        <h3>p.FirstName</h3>
    </div>
}

MVCRosterCalc_DONOTZIP/FootballCalc/Views/Home/Login.cshtml
@{
    ViewData["Title"] = "LogIn";
}
<h1>@ViewData["Title"]</h1>
<body class="login-pg">
<p>Please enter your username and password. If you do not have an account, please click register.</p>
<label for="UserName">Username:</label>
<br>
<input type="text" id="UserName" name="Username">
<br>
<label for="PassWord">Password:</label>
<br>
<input type="text" id="PassWord" name="Password">
<br/>

@*Need data validation*@
<input type="submit" value="Submit">
@*IF data validation is true*@
@*Go to login successful, redirecting to roster page*@
@*IF data validation is false*@


@*Login failed, please try again*@

<btn class="nav-item">
    <a class="nav-link text-dark" asp-controller="Home" asp-action="Register">Register</a>
</btn>
</body>

MVCRosterCalc_DONOTZIP/FootballCalc/Views/Home/Register.cshtml
@*@{
        ViewData["Title"] = "Register";
    }
    <h1>@ViewData["Title"]</h1>

    <p>Please enter your information. Whenever you are done, please press submit.</p>

    <form>
        <label for="UserName">User name:</label><br>
        <input type="text" id="UserName" name="UserName"><br>
        <label for="PassWord">Password:</label><br>
        <input type="text" id="PassWord" name="PassWord"><br />
        <label for="fname">First name:</label><br>
        <input type="text" id="fname" name="fname"><br>
        <label for="lname">Last name:</label><br>
        <input type="text" id="lname" name="lname"><br />
        <label for="dateofBirth">Date of Birth:</label><br>
        <input type="text" id="dateofBirth" name="dateofBirth"><br>
        <label for="Email">Email:</label><br>
        <input type="text" id="Email" name="Email"><br />
        <input type="submit" value="Submit">
    </form>*@

@model FootballCalc.Models.UserModel

@{
    ViewBag.Title = "Registration";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Registration</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<body class="reg-pg">
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserID)

        <div class="form-group">

            @Html.LabelFor(model => model.FirstName, @htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date_Of_Birth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date_Of_Birth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date_Of_Birth, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.UserPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserPassword, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group" name="Email Address">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</body>
}

MVCRosterCalc_DONOTZIP/FootballCalc/Views/Home/Welcome.cshtml
@{
    ViewData["Title"] = "Welcome From Home/Welcome";
}

<h2>Welcome</h2>

<ul>
    @for (int i = 0; i < (int)ViewData["NumTimes"]; i++)
    {
        <li>@ViewData["Message"]</li>
    }
</ul>